<a href="https://colab.research.google.com/github/susmoy15/Machine_Learning/blob/main/Fetching_data_from_an_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd
import requests

In [29]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [30]:
temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [31]:
temp_df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,328.7016,8.969,1382
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,71.0607,8.721,30402
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,47.9630,8.686,22940
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,402.5239,8.600,4101
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,28.1317,8.571,13907

In [32]:
df = pd.DataFrame()         #empty dataframe

In [37]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df = pd.concat([df, temp_df], ignore_index=True)

In [38]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,328.7016,8.969,1382
1,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,1994-09-23,71.0607,8.721,30402
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,47.9630,8.686,22940
3,687163,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,402.5239,8.600,4101
4,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,1974-12-20,28.1317,8.571,13907
...,...,...,...,...,...,...,...
15515,121824,Stand Up Guys,After serving 28 years in prison for accidenta...,2012-12-14,2.1681,6.023,1007
15516,11777,I.Q.,Albert Einstein helps a young man who's in lov...,1994-12-24,1.3797,6.023,491
15517,431075,Polaroid,High school loner Bird Fitcher has no idea wha...,2019-01-10,2.1260,6.022,1135
15518,378018,The Void,"In the middle of a routine patrol, officer Dan...",2016-09-22,2.6572,6.022,1413
15519,21301,Barbershop 2: Back in Business,The continuing adventures of the barbers at Ca...,2004-01-20,1.7968,6.000,316

In [40]:
df.shape

(15520, 7)

In [41]:
df.to_csv('movies.csv')